# Generated by Django 3.0.4 on 2020-03-28 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activerecord',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 8, 17, 37, 90348, tzinfo=utc)),
        ),
    ]
