# Generated by Django 3.0.4 on 2020-03-24 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activerecord',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 12, 59, 51, 849867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 12, 59, 51, 850212, tzinfo=utc)),
        ),
    ]
