# Generated by Django 3.0.4 on 2020-03-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0002_auto_20200329_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='activerecord',
            name='today_jst_str',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
