# Generated by Django 3.0.4 on 2020-05-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0004_activerecord_format_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='KujiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_log', models.IntegerField(null=True)),
                ('cycle_log', models.IntegerField(null=True)),
                ('latest_ver', models.IntegerField(null=True)),
                ('today', models.DateTimeField(null=True)),
                ('subject', models.CharField(max_length=20, null=True)),
                ('today_jst_str', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, null=True)),
                ('gear', models.IntegerField(null=True)),
                ('latest', models.IntegerField(null=True)),
            ],
        ),
    ]
