# Generated by Django 3.0.4 on 2020-05-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0005_kujilog_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activerecord',
            name='memo',
            field=models.CharField(max_length=800, null=True, verbose_name='メモ'),
        ),
    ]
