# Generated by Django 3.0.4 on 2020-05-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0007_auto_20200509_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=20, null=True)),
                ('gear', models.IntegerField(null=True)),
                ('latest', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SubjectID',
        ),
        migrations.RenameField(
            model_name='kujilog',
            old_name='subject',
            new_name='subject_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='gear',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='latest',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
