# Generated by Django 3.0.4 on 2020-05-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0009_auto_20200510_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='latest',
            new_name='latest_ver',
        ),
    ]
