# Generated by Django 3.0.4 on 2020-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0010_auto_20200510_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=6, null=True)),
                ('subject_id', models.CharField(max_length=20, null=True)),
                ('summary', models.CharField(max_length=50, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('version', models.IntegerField(null=True)),
                ('today', models.DateField(null=True)),
                ('tomorrow', models.DateField(null=True)),
                ('one_week_later', models.DateField(null=True)),
                ('two_week_later', models.DateField(null=True)),
                ('one_month_later', models.DateField(null=True)),
            ],
        ),
    ]
