# Generated by Django 3.0.4 on 2020-05-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0012_auto_20200513_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='today',
            field=models.DateTimeField(null=True),
        ),
    ]
