# Generated by Django 3.0.4 on 2020-05-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0014_review_today_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
