# Generated by Django 3.0.4 on 2020-05-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0016_activerecord_study_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='activerecord',
            name='format_study_amount',
            field=models.CharField(max_length=20, null=True, verbose_name=''),
        ),
    ]
