# Generated by Django 3.1 on 2020-09-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0017_activerecord_format_study_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='is_online',
            new_name='subject_type',
        ),
    ]
