# Generated by Django 3.1.1 on 2020-09-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0018_auto_20200905_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='version',
        ),
        migrations.AddField(
            model_name='review',
            name='study_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='study_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
